### ISSUE TITLE
Empty CALLBACK_OBJECTS content when using HTTP callback persistance

### ISSUE THREAD

**Issue by Bogatinovski** [BitPhinix/slate-yjs-example#78]
I am running the server by setting "start:server" command to: `set HOST=localhost&&set PORT=1234&&set CALLBACK_URL=http://localhost:5000/weatherforecast&&set CALLBACK_OBJECTS={\"prosemirror\":\"XmlFragment\"}&& npx y-websocket-server`

Unfortunately when my callback api is hit I receive empty "content" property. The contents of the editor are not supplied. 
**What is the correct CALLBACK_OBJECTS configuration** in order to receive the editor content which I can persist through my API?

Thanks!

**Comment by BitPhinix** [comment]
Hi @Bogatinovski,

I'm sorry but I can't really help you with this issue and it isn't really related to the project. You might want to ask here: https://discuss.yjs.dev/ or open an issue here: https://github.com/yjs/y-websocket
